### PR TITLE
Update javacc grammar to allow optional trailing commas

### LINKED ISSUE #47: Allow trailing commas `,` before the closing bracket `}`
JSON does not allow trailing commas like in

    { 
      "@id": 1,
    }

The comma after 1 will make the parser believe a new key is expected. This is usually an annoyance and JSLT could support trailing commas to make it easier to write JSLT templates, without worrying about the commas

### PR DESCRIPTION
**Pull request by ecerulm**
Closes #47

### CODE REVIEW

**Comment by ecerulm** [comment]
This make the following JSTL valid
 
```
{
  "a": 1,
}
```

note the trailing `,` after the 1 which is not allowed in JSON

**Comment by larsga** [comment]
I've had to do a few rounds with myself on this issue, because this is our first step outside the policy of strictly following JSON syntax. Realizing that comments already are one step outside JSON helped me decide. Anyway, I've decided I like this.

However, there are some things I'd like to see changed here:

1. We need to support trailing commas in arrays, too. (With tests, obviously.)
1. The negative test (showing we detect the parse error) can go into `src/test/resources/json-parse-error-tests.json`.

I'd like to see the positive test handled via JSON files, too, but I realize that's harder, so we can leave that one as is for now.

Can you do this? Otherwise I can take care of it.

**Comment by ecerulm** [comment]
Yes, I can add the support for trailing commas in arrrays. 

I'm not sure what negative tests to add. The only thing it comes to mind is:
* double trailing commas should be an  error `{"a" : 1,,}`
* also in arrays `[1,2,,]` . 

Are there other negatives cases you had in mind?

**Comment by larsga** [comment]
Great. You already have one negative test for objects, so if you just move it to the JSON file that will do fine. Then a similar negative test for arrays. I think that's enough.

**Comment by ecerulm** [comment]
Done.  I had to insert a new grammar rule `ArrayElem` that doesn't produce nodes just to be able to cope with the no-double-trailing comma case. That probably doesn't have any impact beside limiting the number of elements that a literal array can have (limited by the java stack, since each element makes the parse go one level deeper in the call stack). If I understand it right the number of pairs in an object is limited in the same way.

**Comment by larsga** [comment]
Good work. Thank you, @ecerulm !

**Pull request merged**
