### PR TITLE
pom.xml that builds library and fat jar

### PR DESCRIPTION
**Pull request by wdonne**
It adds the steps to run jjtree and javacc. It also assembles a fat jar for the command-line when you do "mvn package".

### CODE REVIEW

**Comment by larsga** [comment]
Hmmmm. I've kind of settled on gradle as the build tool, and I'm not very keen to maintain two sets of build files.

What's the motivation for turning the `pom.xml` file into a real build file? What does it give us, except more work?

**Comment by wdonne** [comment]
I saw the pom file was in the package. What I added to it can surely also be added to the gradle file. Perhaps the pom file can be remove altogether then?

**Comment by larsga** [comment]
The gradle file already has this.

`./gradlew jar` gives you the ordinary library jar.

`./gradlew shadowJar` gives you the fat jar.

The `pom.xml` file is only there to enable the Github dependency tracking for this repo. It's not meant to actually be used for anything else.

**Comment by wdonne** [comment]
I see. Thanks for clarifying that.

**Comment by larsga** [comment]
I guess actually building might be tricky for people who are not use to Gradle. Should I add a brief section on how to build jar and fat jar with gradle, plus how to run tests?

**Comment by wdonne** [comment]
That is a great idea. It will be convenient and the tests will run more often.

**Comment by larsga** [comment]
Done. I guess we can close this now, then?

**Comment by wdonne** [comment]
Yes. Thank you very much!

**Pull request closed without merging**
