### PR TITLE
Use Math.round() instead of (long) when casting in format-time()

### PR DESCRIPTION
**Pull request by vectro**

### CODE REVIEW

**Comment by larsga** [comment]
Very nice work. Thank you!

As you'll see above, this PR contains the commit you want, plus two earlier ones. The way to solve this is to go back to master, then start a new branch from there. If you start the branch from a branch you've already done work on, that existing history gets dragged into this PR.

Could you rebase this on master and do a force push? That will clean up the history.

**Comment by vectro** [comment]
I would have thought that github would handle merging that automatically? But I am happy to rebase.

**Comment by larsga** [comment]
I used to think github would do that, too, but the problem is the commits are not actually the same any more. I think the reason is that the history of a commit is a part of the identity of the commit. So the same change applied two different places in the version history is not the same commit.

Somehow it got even worse now. I'm not sure what happened. The normal workflow to sort this out is:

```
git checkout master
git pull
git checkout roundout
git rebase master
git push -f
```

I _think_. I always do this via magit in Emacs where it's much easier.

**Comment by vectro** [comment]
Are you sure? Github is telling me that "merging can be performed automatically".

When I look at the long, this commit is based on your last merge:
https://github.com/vectro/jslt/commits/roundout

**Comment by larsga** [comment]
When you look at the top of the PR page you see there are 6 commits (the commits tab). But we only actually want one.

I can fix it by pulling that single commit out of your branch and onto master, if you think this is getting complicated. (I could of course also just copy your code and replicate the commit, but it feels unfair. The commit should be attached to you so that you get the credit for it.)

**Comment by vectro** [comment]
I have cleaned up the comments and moved this to new pull request #15.

**Comment by larsga** [comment]
Excellent. Thanks!

**Pull request closed without merging**
